// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           12
// Async Callback (empty):               1
// Total number of exported functions:  14

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    nft_staking
    (
        init => init
        stake => stake
        startUnbonding => start_unbonding
        claimUnbonded => claim_unbonded
        claimRewards => claim_rewards
        getStakingPoolTypeConfiguration => stake_pool_type_configuration
        getStakedNfts => staked_nfts
        getUserDeb => user_deb
        getAggregatedStakingScore => aggregated_staking_score
        getAggregatedUserStakingScore => aggregated_user_staking_score
        getBaseAssetScore => base_asset_score
        getNonceAssetScore => nonce_asset_score
        getFullSetScore => full_set_score
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
